### PR TITLE
Adding a few missing methods on the mock schema.

### PR DESCRIPTION
**Pull request by boushley**
index -- http://mongoosejs.com/docs/api.html#schematype_SchemaType-index
plugin -- http://mongoosejs.com/docs/api.html#schema_Schema-plugin
set -- http://mongoosejs.com/docs/api.html#schematype_SchemaType-set

### CODE REVIEW

**Comment by JohanObrink** [comment]
Thanks!

**Comment by boushley** [comment]
Any ideas when you are going to publish the 0.4.0 version?

**Comment by JohanObrink** [comment]
Sorry! Had some issues with npm publish. It's out now. Thanks for the help :)

**Comment by boushley** [comment]
Awesome! Thanks for getting that out.

And thanks for the project, save me a bunch of time.

**Pull request merged**
